# Introduction to Numpy
> Chapter 2 - Basics of numpy
>> NumPy is a powerful library for numerical computing in Python. Here's a simple script introducing some basic NumPy functionality for beginners:
>>> Reach us at https://topmate.io/datanddoodle

This script covers the creation of NumPy arrays, basic arithmetic operations, indexing, slicing, working with multi-dimensional arrays, generating sequences of numbers, reshaping arrays, and generating random numbers. 
Feel free to run this script in a Python environment to see the output.

# Import NumPy library

In [1]:
import numpy as np

# Creating NumPy Arrays

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

# Displaying Arrays

In [3]:
print("Array 1:", arr1)
print("Array 2:", arr2)

Array 1: [1 2 3 4 5]
Array 2: [ 6  7  8  9 10]


# Basic Arithmetic Operations - Arrays

In [4]:
sum_array = arr1 + arr2
difference_array = arr1 - arr2
product_array = arr1 * arr2
division_array = arr1 / arr2

In [5]:
print("Sum of arrays:", sum_array)
print("Difference of arrays:", difference_array)
print("Product of arrays:", product_array)
print("Division of arrays:", division_array)

Sum of arrays: [ 7  9 11 13 15]
Difference of arrays: [-5 -5 -5 -5 -5]
Product of arrays: [ 6 14 24 36 50]
Division of arrays: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


# Array Indexing and Slicing

In [6]:
print("Element at index 2 in Array 1:", arr1[2])
print("Elements from index 1 to 3 in Array 2:", arr2[1:4])

Element at index 2 in Array 1: 3
Elements from index 1 to 3 in Array 2: [7 8 9]


# Multi-Dimensional Arrays

In [7]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Matrix:")
print(matrix)

2D Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Operations on Multi-Dimensional Arrays

In [8]:
row_sum = np.sum(matrix, axis=1)
column_mean = np.mean(matrix, axis=0)

In [9]:
print("Sum of each row:", row_sum)
print("Mean of each column:", column_mean)

Sum of each row: [ 6 15 24]
Mean of each column: [4. 5. 6.]


# Generating sequences of numbers

In [10]:
sequence = np.arange(0, 10, 2)  # Start, stop, step
print("Sequence of numbers:", sequence)

Sequence of numbers: [0 2 4 6 8]


# Reshaping Arrays

In [11]:
reshaped_matrix = matrix.reshape(1, 9)
print("Reshaped Matrix:")
print(reshaped_matrix)

Reshaped Matrix:
[[1 2 3 4 5 6 7 8 9]]


# Random number generation

In [12]:
random_array = np.random.rand(3, 3)  # 3x3 array of random numbers between 0 and 1
print("Random 3x3 Array:")
print(random_array)

Random 3x3 Array:
[[0.85537846 0.50481211 0.71551163]
 [0.45095224 0.6542107  0.80186775]
 [0.54907797 0.77430897 0.08031943]]
